sudo: required
services:
  - docker

before_install:
  - docker build -t goncalomarques28/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true goncalomarques28/react-test npm test -- --coverage

after_success:
  - docker build -t goncalomarques28/multi-container-client ./client
  - docker build -t goncalomarques28/multi-container-nginx ./nginx
  - docker build -t goncalomarques28/multi-container-server ./server
  - docker build -t goncalomarques28/multi-container-worker ./worker
  #log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push goncalomarques28/multi-container-client
  - docker push goncalomarques28/multi-container-nginx
  - docker push goncalomarques28/multi-container-server
  - docker push goncalomarques28/multi-container-worker
